2022-11-20 01:08:07,780 INFO    MainThread:1584 [wandb_setup.py:_flush():68] Configure stats pid to 1584
2022-11-20 01:08:07,780 INFO    MainThread:1584 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Sebastian Cavada\.config\wandb\settings
2022-11-20 01:08:07,780 INFO    MainThread:1584 [wandb_setup.py:_flush():68] Loading settings from c:\Users\Sebastian Cavada\Documents\SCSV\Projects\HackaTUM\machine-learning\pytorch\train\wandb\settings
2022-11-20 01:08:07,780 INFO    MainThread:1584 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-20 01:08:07,780 INFO    MainThread:1584 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-20 01:08:07,781 INFO    MainThread:1584 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2022-11-20 01:08:07,782 INFO    MainThread:1584 [wandb_init.py:_log_setup():476] Logging user logs to c:\Users\Sebastian Cavada\Documents\SCSV\Projects\HackaTUM\machine-learning\pytorch\train\wandb\run-20221120_010807-1dw0kfti\logs\debug.log
2022-11-20 01:08:07,782 INFO    MainThread:1584 [wandb_init.py:_log_setup():477] Logging internal logs to c:\Users\Sebastian Cavada\Documents\SCSV\Projects\HackaTUM\machine-learning\pytorch\train\wandb\run-20221120_010807-1dw0kfti\logs\debug-internal.log
2022-11-20 01:08:07,782 INFO    MainThread:1584 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000026F8C305700>
2022-11-20 01:08:07,782 INFO    MainThread:1584 [wandb_init.py:init():516] calling init triggers
2022-11-20 01:08:07,782 INFO    MainThread:1584 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-20 01:08:07,782 INFO    MainThread:1584 [wandb_init.py:init():569] starting backend
2022-11-20 01:08:07,782 INFO    MainThread:1584 [wandb_init.py:init():573] setting up manager
2022-11-20 01:08:07,794 INFO    MainThread:1584 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-11-20 01:08:07,801 INFO    MainThread:1584 [wandb_init.py:init():580] backend started and connected
2022-11-20 01:08:07,805 INFO    MainThread:1584 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-11-20 01:08:07,805 INFO    MainThread:1584 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-11-20 01:08:07,805 INFO    MainThread:1584 [wandb_init.py:init():658] updated telemetry
2022-11-20 01:08:07,850 INFO    MainThread:1584 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-20 01:08:11,002 WARNING MsgRouterThr:1584 [router.py:message_loop():77] message_loop has been closed
2022-11-20 01:08:12,908 ERROR   MainThread:1584 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "c:\Users\Sebastian Cavada\anaconda3\envs\cv\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "c:\Users\Sebastian Cavada\anaconda3\envs\cv\lib\site-packages\wandb\sdk\wandb_init.py", line 697, in init
    result = handle.wait(
  File "c:\Users\Sebastian Cavada\anaconda3\envs\cv\lib\site-packages\wandb\sdk\lib\mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
